---
kind: ConfigMap
apiVersion: v1
metadata:
  name: config
  labels:
    app: datamart
data:
  elasticsearch.cluster_name: "docker-cluster"
  elasticsearch.heap_size: "4g"
  query_host: http://192.168.99.100:30081
  redis.conf: |
    maxmemory 500mb
    maxmemory-policy allkeys-lru
  s3.url: http://minio:9000
  s3.client_url: http://192.168.99.100:30900
  s3.bucket_prefix: dev-
  gcs.bucket_prefix: dev-
