---
kind: ConfigMap
apiVersion: v1
metadata:
  name: config
  labels:
    app: datamart
data:
  elasticsearch.cluster_name: "docker-cluster"
  elasticsearch.heap_size: "4g"
  api_url: http://192.168.99.100:30081
  redis.conf: |
    maxmemory 500mb
    maxmemory-policy allkeys-lru
