---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: rabbitmq
  labels:
    app: datamart
    what: rabbitmq
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: datamart
        what: rabbitmq
    spec:
      containers:
      - name: rabbitmq
        image: remram/rabbitmq:3.7.8
        env:
        - name: RABBITMQ_DEFAULT_USER
          valueFrom:
            secretKeyRef:
              name: secrets
              key: amqp.user
        - name: RABBITMQ_DEFAULT_PASS
          valueFrom:
            secretKeyRef:
              name: secrets
              key: amqp.password
        ports:
        - containerPort: 5672
        - containerPort: 15672
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: redis
  labels:
    app: datamart
    what: redis
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: datamart
        what: redis
    spec:
      containers:
      - name: redis
        image: redis:5.0
        args: ["redis-server", "/usr/local/etc/redis/redis.conf"]
        ports:
        - containerPort: 6379
        volumeMounts:
        - name: config
          mountPath: /usr/local/etc/redis
      volumes:
      - name: config
        configMap:
          name: config
          items:
          - key: redis.conf
            path: redis.conf
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: lazo
  labels:
    app: datamart
    what: lazo
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: datamart
        what: lazo
    spec:
      containers:
      - name: lazo
        image: registry.gitlab.com/vida-nyu/datamart/lazo-index-service:0.2.0
        env:
        - name: DATABASE
          value: elasticsearch
        - name: PORT
          value: "50051"
        - name: ELASTICSEARCH_HOST
          value: elasticsearch
        - name: ELASTICSEARCH_PORT
          value: "9200"
        ports:
        - containerPort: 50051
        volumeMounts:
        - mountPath: /datasets
          name: datasets
        - mountPath: /cache
          name: cache
      volumes:
      - name: datasets
        persistentVolumeClaim:
          claimName: datasets
      - name: cache
        persistentVolumeClaim:
          claimName: cache
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: datamart
    what: frontend
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: datamart
        what: frontend
    spec:
      containers:
      - name: web
        image: datamart_frontend
        imagePullPolicy: IfNotPresent
        env:
        - name: API_URL
          valueFrom:
            configMapKeyRef:
              name: config
              key: api_url
        ports:
        - containerPort: 80
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: apiserver
  labels:
    app: datamart
    what: apiserver
spec:
  replicas: 4
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: datamart
        what: apiserver
    spec:
      containers:
      - name: web
        image: datamart_apiserver
        imagePullPolicy: IfNotPresent
        env:
        - name: ELASTICSEARCH_HOSTS
          value: elasticsearch:9200
        - name: AMQP_HOST
          value: rabbitmq
        - name: AMQP_PORT
          value: "5672"
        - name: AMQP_USER
          valueFrom:
            secretKeyRef:
              name: secrets
              key: amqp.user
        - name: AMQP_PASSWORD
          valueFrom:
            secretKeyRef:
              name: secrets
              key: amqp.password
        - name: REDIS_HOST
          value: redis
        - name: LAZO_SERVER_HOST
          value: lazo
        - name: LAZO_SERVER_PORT
          value: "50051"
        - name: NOMINATIM_URL
          valueFrom:
            configMapKeyRef:
              name: config
              key: nominatim_url
        ports:
        - containerPort: 8002
        volumeMounts:
        - mountPath: /datasets
          name: datasets
        - mountPath: /cache
          name: cache
        readinessProbe:
          httpGet:
            path: /health
            port: 8002
          periodSeconds: 1
          failureThreshold: 2
      volumes:
      - name: datasets
        persistentVolumeClaim:
          claimName: datasets
      - name: cache
        persistentVolumeClaim:
          claimName: cache
      terminationGracePeriodSeconds: 600
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: coordinator
  labels:
    app: datamart
    what: coordinator
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: datamart
        what: coordinator
    spec:
      containers:
      - name: web
        image: datamart_coordinator
        imagePullPolicy: IfNotPresent
        env:
        - name: ELASTICSEARCH_HOSTS
          value: elasticsearch:9200
        - name: AMQP_HOST
          value: rabbitmq
        - name: AMQP_PORT
          value: "5672"
        - name: AMQP_USER
          valueFrom:
            secretKeyRef:
              name: secrets
              key: amqp.user
        - name: AMQP_PASSWORD
          valueFrom:
            secretKeyRef:
              name: secrets
              key: amqp.password
        - name: API_URL
          valueFrom:
            configMapKeyRef:
              name: config
              key: api_url
        - name: MAX_CACHE_BYTES
          value: "100000000000"  # 100 GB
        ports:
        - containerPort: 8003
        volumeMounts:
        - mountPath: /datasets
          name: datasets
        - mountPath: /cache
          name: cache
      volumes:
      - name: datasets
        persistentVolumeClaim:
          claimName: datasets
      - name: cache
        persistentVolumeClaim:
          claimName: cache
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: profiler
  labels:
    app: datamart
    what: profiler
spec:
  replicas: 4
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 2
  template:
    metadata:
      labels:
        app: datamart
        what: profiler
    spec:
      containers:
      - name: web
        image: datamart_profiler
        imagePullPolicy: IfNotPresent
        env:
        - name: ELASTICSEARCH_HOSTS
          value: elasticsearch:9200
        - name: AMQP_HOST
          value: rabbitmq
        - name: AMQP_PORT
          value: "5672"
        - name: AMQP_USER
          valueFrom:
            secretKeyRef:
              name: secrets
              key: amqp.user
        - name: AMQP_PASSWORD
          valueFrom:
            secretKeyRef:
              name: secrets
              key: amqp.password
        - name: LAZO_SERVER_HOST
          value: lazo
        - name: LAZO_SERVER_PORT
          value: "50051"
        - name: NOMINATIM_URL
          valueFrom:
            configMapKeyRef:
              name: config
              key: nominatim_url
        volumeMounts:
        - mountPath: /datasets
          name: datasets
        - mountPath: /cache
          name: cache
      volumes:
      - name: datasets
        persistentVolumeClaim:
          claimName: datasets
      - name: cache
        persistentVolumeClaim:
          claimName: cache
