---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: elasticsearch
  labels:
    app: datamart
    what: elasticsearch
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: datamart
        what: elasticsearch
    spec:
      initContainers:
      - name: fix-permissions
        image: busybox
        command: ["sh", "-c", "chown -R 1000:1000 /usr/share/elasticsearch/data"]
        volumeMounts:
        - name: data
          mountPath: /usr/share/elasticsearch/data
      - name: increase-vm-max-map
        image: busybox
        command: ["sysctl", "-w", "vm.max_map_count=262144"]
        securityContext:
          privileged: true
      containers:
      - name: elasticsearch
        image: docker.elastic.co/elasticsearch/elasticsearch:7.6.0
        env:
        - name: cluster.name
          value: datamart-cluster
        - name: ES_JAVA_OPTS
          value: -Des.enforce.bootstrap.checks=true
        - name: discovery.type
          value: single-node
        # This needs special permissions that I don't know how to grant
        # - name: bootstrap.memory_lock
        #   value: "true"
        - name: ES_HEAP_SIZE
          valueFrom:
            configMapKeyRef:
              name: config
              key: elasticsearch.heap_size
        ports:
        - containerPort: 9200
        volumeMounts:
        - mountPath: /usr/share/elasticsearch/data
          name: data
        readinessProbe:
          httpGet:
            scheme: HTTP
            path: /_cluster/health?local=true
            port: 9200
          initialDelaySeconds: 5
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: elasticsearch
