---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: dm-secrets
data:
  # Those values need to be encoded in base64
  amqp.user: ZGF0YW1hcnQ= # "datamart"
  amqp.password: ZGF0YW1hcnQ= # "datamart"
