---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: datasets
spec:
  storageClassName: "csi-cephfs-sc"
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: cache
spec:
  storageClassName: "csi-cephfs-sc"
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
