image: python:3.7

test_actual:
  script:
    - diff -u lib_core/datamart_core/types.py lib_profiler/datamart_profiler/types.py && diff -u lib_core/datamart_core/types.py lib_materialize/datamart_materialize/types.py
    - echo $?

test_diff:
  script:
    - diff -u lib_core/datamart_core/types.py lib_profiler/datamart_profiler/types.py
    - echo $?

test_conds_1:
  script:
    - false && true
    - echo $?
test_conds_2:
  script:
    - true && false
    - echo $?
