version: '3'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.4.0
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - 8080:15672
      - 5672:5672
  coordinator:
    build:
      context: .
      dockerfile: datamart_coordinator/Dockerfile
    environment:
      - ELASTICSEARCH_HOSTS=elasticsearch:9200
    ports:
     - 8001:8001
    volumes:
      - datasets:/datasets
  example_discoverer:
    build:
      context: .
      dockerfile: examples/Dockerfile
    command: discovery
    environment:
      - ELASTICSEARCH_HOSTS=elasticsearch:9200
      - COORDINATOR_URL=http://coordinator:8001
    volumes:
      - datasets:/datasets
  example_ingester:
    build:
      context: .
      dockerfile: examples/Dockerfile
    command: ingestion
    environment:
      - ELASTICSEARCH_HOSTS=elasticsearch:9200
      - COORDINATOR_URL=http://coordinator:8001
    volumes:
      - datasets:/datasets
volumes:
  datasets:
