version: '3'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.4.0
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      # Enabling CORS
      - http.cors.enabled=true
      - http.cors.allow-origin=http://localhost:3000
      - http.cors.allow-headers=Content-Type, Access-Control-Allow-Headers, Authorization, X-Requested-With
      - http.cors.allow-credentials=true
      # JVM options
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
  kibana:
    image: docker.elastic.co/kibana/kibana:6.4.2
    environment:
      # SERVER_NAME: kibana.example.org
      ELASTICSEARCH_URL: http://elasticsearch:9200
    ports:
      - 5601:5601
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - 8080:15672
      - 5672:5672
  coordinator:
    build:
      context: .
      dockerfile: datamart_coordinator/Dockerfile
    command: python -m datamart_coordinator.web
    environment:
      - ELASTICSEARCH_HOSTS=elasticsearch:9200
      - AMQP_HOST=rabbitmq
      - AMQP_USER=guest
      - AMQP_PASSWORD=guest
      - QUERY_HOST=http://localhost:8002
    ports:
      - 8001:8001
    volumes:
      - datasets:/datasets
      - ./datamart_coordinator/datamart_coordinator:/usr/src/app/datamart_coordinator/datamart_coordinator
  query:
    build:
      context: .
      dockerfile: datamart_query/Dockerfile
    command: python -m datamart_query.web
    environment:
      - ELASTICSEARCH_HOSTS=elasticsearch:9200
      - AMQP_HOST=rabbitmq
      - AMQP_USER=guest
      - AMQP_PASSWORD=guest
    ports:
      - 8002:8002
    volumes:
      - datasets:/datasets
      - ./datamart_query/datamart_query:/usr/src/app/datamart_query/datamart_query
  profiler:
    build:
      context: .
      dockerfile: datamart_profiler/Dockerfile
    environment:
      - ELASTICSEARCH_HOSTS=elasticsearch:9200
      - AMQP_HOST=rabbitmq
      - AMQP_USER=guest
      - AMQP_PASSWORD=guest
    volumes:
      - datasets:/datasets
  example_discoverer:
    build:
      context: .
      dockerfile: examples/Dockerfile
    command: discovery
    environment:
      - ELASTICSEARCH_HOSTS=elasticsearch:9200
      - AMQP_HOST=rabbitmq
      - AMQP_USER=guest
      - AMQP_PASSWORD=guest
    volumes:
      - datasets:/datasets
  example_d3m_discoverer:
    build:
      context: .
      dockerfile: examples/Dockerfile
    command: d3m
    environment:
      - ELASTICSEARCH_HOSTS=elasticsearch:9200
      - AMQP_HOST=rabbitmq
      - AMQP_USER=guest
      - AMQP_PASSWORD=guest
    volumes:
      - datasets:/datasets
      - ../datasets/seed_datasets_current:/d3m_seed_datasets
volumes:
  datasets:
