version: '3'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.4.0
    restart: on-failure
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - 8080:15672
      - 5672:5672
  coordinator:
    build:
      context: .
      dockerfile: coordinator/Dockerfile
    command: python -m coordinator.web
    environment:
      - ELASTICSEARCH_HOSTS=elasticsearch:9200
      - AMQP_HOST=rabbitmq
      - AMQP_USER=guest
      - AMQP_PASSWORD=guest
      - QUERY_HOST=http://localhost:8002
    ports:
      - 8001:8001
    volumes:
      - datasets:/datasets
      - ./coordinator/coordinator:/usr/src/app/coordinator/coordinator
  query:
    build:
      context: .
      dockerfile: query/Dockerfile
    command: python -m query.web
    environment:
      - ELASTICSEARCH_HOSTS=elasticsearch:9200
      - AMQP_HOST=rabbitmq
      - AMQP_USER=guest
      - AMQP_PASSWORD=guest
    ports:
      - 8002:8002
    volumes:
      - datasets:/datasets
      - ../data/seed_datasets_current:/d3m_seed_datasets
      - ./query/query:/usr/src/app/query/query
  profiler:
    build:
      context: .
      dockerfile: profiler/Dockerfile
    environment:
      - ELASTICSEARCH_HOSTS=elasticsearch:9200
      - AMQP_HOST=rabbitmq
      - AMQP_USER=guest
      - AMQP_PASSWORD=guest
    volumes:
      - datasets:/datasets
      - ../data/seed_datasets_current:/d3m_seed_datasets
  example_discoverer:
    build:
      context: .
      dockerfile: discovery/Dockerfile
    command: example
    environment:
      - ELASTICSEARCH_HOSTS=elasticsearch:9200
      - AMQP_HOST=rabbitmq
      - AMQP_USER=guest
      - AMQP_PASSWORD=guest
    volumes:
      - datasets:/datasets
  d3m_seeds:
    build:
      context: .
      dockerfile: discovery/Dockerfile
    command: d3m
    environment:
      - ELASTICSEARCH_HOSTS=elasticsearch:9200
      - AMQP_HOST=rabbitmq
      - AMQP_USER=guest
      - AMQP_PASSWORD=guest
    volumes:
      - datasets:/datasets
      - ../data/seed_datasets_current:/d3m_seed_datasets
  socrata:
    build:
      context: .
      dockerfile: discovery/socrata/Dockerfile
    environment:
      - ELASTICSEARCH_HOSTS=elasticsearch:9200
      - AMQP_HOST=rabbitmq
      - AMQP_USER=guest
      - AMQP_PASSWORD=guest
    volumes:
      - datasets:/datasets
  noaa:
    build:
      context: .
      dockerfile: discovery/noaa/Dockerfile
    environment:
      - ELASTICSEARCH_HOSTS=elasticsearch:9200
      - AMQP_HOST=rabbitmq
      - AMQP_USER=guest
      - AMQP_PASSWORD=guest
      - NOAA_TOKEN=${NOAA_TOKEN}
    volumes:
      - datasets:/datasets
volumes:
  datasets:
