[tool.poetry]
name = "datamart"
version = "0.5"
description = "Datamart system meta-package"

license = "BSD-3-Clause"

authors = [
    "Remi Rampin <remi.rampin@nyu.edu>",
]

repository = "https://gitlab.com/ViDA-NYU/datamart/datamart"
homepage = "https://auctus.vida-nyu.org/"

keywords = ["datamart"]

classifiers = [
    "Development Status :: 2 - Pre-Alpha",
    "Intended Audience :: Science/Research",
    "Natural Language :: English",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3 :: Only",
    "Topic :: Scientific/Engineering :: Information Analysis",
]

packages = []

include = []

[tool.poetry.dependencies]
python = "^3.7"
datamart_profiler = {path = "./lib_profiler"}
datamart_materialize = {path = "./lib_materialize"}
datamart_augmentation = {path = "./lib_augmentation"}
datamart_core = {path = "./lib_core"}
datamart-coordinator-service = {path = "./coordinator"}
datamart-profiler-service = {path = "./profiler"}
datamart-api-service = {path = "./apiserver"}
datamart-noaa_discovery-service = {path = "./discovery/noaa"}
datamart-socrata-discovery-service = {path = "./discovery/socrata"}
datamart-zenodo-discovery-service = {path = "./discovery/zenodo"}

[tool.poetry.dev-dependencies]
flake8 = "*"
PyYaml = "*"
requests = "*"
coverage = "*" # Keep it in sync with Dockerfiles for CI
jsonschema = ">=3.0,<4"
readme_renderer = "*"
Sphinx = "*"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
